### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by murphydanger** [twitter/recess#154]
What't the deal with the branch `v2.0.0`? Is it being maintained, what are the goals of it, when will it replace `master`, etc.?

**Comment by hiebj** [comment]
Any response here on the initial question? Is there an estimated time frame for 2.0? Based on commit frequency I assume it is relatively far off, but I'd be eager to use Recess again if it ever supports more modern versions of Less. As it stands there is no comparable Less linter.

**Comment by jonathanepollack** [comment]
Yeah, I changed jobs, and this literally got buried under a pile of todo's. It doesn't look like any one else has much more free time either though...
